# Generated by Django 4.2.2 on 2023-08-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMediaManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='chats',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
