# Generated by Django 4.2.2 on 2023-07-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMediaManagementSystem', '0003_users_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=10),
        ),
    ]
