# Generated by Django 4.2.2 on 2023-08-29 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMediaManagementSystem', '0005_rename_created_at_chats_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='encrypted_symmetric_key',
        ),
    ]
