# Generated by Django 4.2.2 on 2023-08-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMediaManagementSystem', '0006_remove_chats_encrypted_symmetric_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='encrypted_symmetric_key',
            field=models.BinaryField(null=True),
        ),
    ]
