# Generated by Django 4.2.2 on 2023-08-30 17:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMediaManagementSystem', '0007_chats_encrypted_symmetric_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='encrypted_message',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='encrypted_symmetric_key',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='signature',
        ),
        migrations.AddField(
            model_name='chats',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='chats',
            name='message_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='chats',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chats',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_chats', to='SocialMediaManagementSystem.users'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_chats', to='SocialMediaManagementSystem.users'),
        ),
    ]
